//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesija
    {
        public long sesija_id { get; set; }
        public System.DateTime vrijeme_kreiranja { get; set; }
        public Nullable<System.DateTime> vrijeme_zavrsetka { get; set; }
        public Nullable<bool> je_aktivna { get; set; }
        public long korisnik { get; set; }
    
        public virtual tblOsoba tblOsoba { get; set; }
    }
}
