//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKomentar
    {
        public long komentar_id { get; set; }
        public Nullable<long> kreator { get; set; }
        public string tekst { get; set; }
    
        public virtual tblOsoba tblOsoba { get; set; }
    }
}
