//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOsoba
    {
        public tblOsoba()
        {
            this.tblKomentar = new HashSet<tblKomentar>();
            this.tblKupac = new HashSet<tblKupac>();
            this.tblUposlenik = new HashSet<tblUposlenik>();
            this.tblZahtjev = new HashSet<tblZahtjev>();
        }
    
        public long osoba_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public bool je_zensko { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<tblKomentar> tblKomentar { get; set; }
        public virtual ICollection<tblKupac> tblKupac { get; set; }
        public virtual ICollection<tblUposlenik> tblUposlenik { get; set; }
        public virtual ICollection<tblZahtjev> tblZahtjev { get; set; }
    }
}
