//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPoklon
    {
        public long poklon_id { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public string slika { get; set; }
        public string opis { get; set; }
        public Nullable<long> prodao { get; set; }
        public Nullable<long> proizveo { get; set; }
        public string naziv { get; set; }
    
        public virtual tblProdavač tblProdavač { get; set; }
        public virtual tblProizvodjac tblProizvodjac { get; set; }
    }
}
