//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProdavač
    {
        public long prodavac_id { get; set; }
        public long uposlenik_id { get; set; }
        public long poslovnica_id { get; set; }
        public string napomena { get; set; }
    
        public virtual tblUposlenik tblUposlenik { get; set; }
    }
}
