//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPoslovnica
    {
        public long poslovnica_id { get; set; }
        public Nullable<System.DateTime> vrijeme_otvaranja_dnevno { get; set; }
        public Nullable<System.DateTime> vrijeme_zatvaranja_dnevno { get; set; }
        public Nullable<System.DateTime> vrijeme_otvaranja_poslovnice { get; set; }
    }
}
