//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokloni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUposlenik
    {
        public tblUposlenik()
        {
            this.tblProdavač = new HashSet<tblProdavač>();
            this.tblProizvodjac = new HashSet<tblProizvodjac>();
        }
    
        public long uposlenik_id { get; set; }
        public long osoba_id { get; set; }
        public long broj_radne_knjizice { get; set; }
        public System.DateTime datum_uposlenja { get; set; }
        public decimal plata { get; set; }
        public Nullable<decimal> dodatak_na_platu { get; set; }
    
        public virtual tblOsoba tblOsoba { get; set; }
        public virtual ICollection<tblProdavač> tblProdavač { get; set; }
        public virtual ICollection<tblProizvodjac> tblProizvodjac { get; set; }
    }
}
